# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.4.1
    working_directory: /InvoiceManager/
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      SCAN_DEVICE: iPhone 8
      SCAN_SCHEME: InvoiceManager 

    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  # swiftlint:
  #   docker:
  #     - image: dantoml/swiftlint:latest
  #       auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout
  #     # - swiftlint:
  #         # path: "" 
  #     - run: swiftlint lint --reporter junit | tee result.xml
  #     - store_artifacts:
  #         path: result.xml
  #     - store_test_results:
  #         path: result.xml

  adhoc:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  build:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output


workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      # - swiftlint
      # - build
      - adhoc:
          filters:
            branches:
              only: development #development branch
          requires:
            - build-and-test